### ISSUE TITLE
Suggestion for relative path to config folder

### ISSUE THREAD

**Issue by AbsolemJackdaw** [magistermaks/fabric-simplelibs#1]
https://github.com/magistermaks/fabric-simplelibs/blob/master/simple-config/SimpleConfig.java#L100
`        Path path = FabricLoader.getInstance().getConfigDir();
`

if you change the path obtained by the fabric loader to a relative path, including the config folder, it works just the same and could be used for forge as well !
`Path path = Path.of("./config");`

I didn't make a pull request because I do not know your intend with the SimpleConfig.
I have used this fix myself to make a simple configuration file to use with my mod that I'm currently coding under Multiloader (forge and fabric simultaneously) and prevents the slop of having to add two different configs for both versions. 

I haven't thoroughly tested this, but it seems to work grand for what I'm using it for so far !

**Comment by magistermaks** [comment]
hmm i see nothing against this, you can PR that in

**Comment by magistermaks** [comment]
resolved in #2
